{% set version = "1.5.0" %}

package:
  name: prov
  version: {{ version }}

source:
  fn: prov-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/p/prov/prov-{{ version }}.tar.gz
  sha256: 96a74efa1b3324961ff66246539ed7bdc06245dcbeef538688c755a0ad5777ee

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - python-dateutil >=2.2
    - networkx >=1.10
    - lxml >=3.3.5
    - pydotplus >=2.0.2
    - six >=1.9.0
    - rdflib >=4.2.1

  run:
    - python
    - python-dateutil >=2.2
    - networkx >=1.10
    - lxml >=3.3.5
    - pydotplus >=2.0.2
    - six >=1.9.0
    - rdflib >=4.2.1

test:
  # Python imports
  imports:
    - prov
    - prov.serializers
    - prov.tests

about:
  home: https://github.com/trungdong/prov
  license: MIT
  summary: 'A library for W3C Provenance Data Model supporting PROV-JSON and PROV-XML'

extra:
  recipe-maintainers:
    - chrisfilo
    - satra
    - trungdong
