{% set version = "1.5.2" %}

package:
  name: prov
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/trungdong/prov/archive/{{ version }}.tar.gz
  sha256: ac41970790216565b04db70a05c763a65b5cd48ca52c4e650e4b9e5e999c1ae0

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - python-dateutil >=2.2
    - networkx >=2.0
    - lxml >=3.3.5
    - pydotplus >=2.0.2
    - six >=1.9.0
    - rdflib >=4.2.2

  run:
    - python
    - python-dateutil >=2.2
    - networkx >=2.0
    - lxml >=3.3.5
    - pydotplus >=2.0.2
    - six >=1.9.0
    - rdflib >=4.2.2

test:
  # Python imports
  imports:
    - prov
    - prov.serializers
    - prov.tests

about:
  home: https://github.com/trungdong/prov
  license: MIT
  summary: 'A library for W3C Provenance Data Model supporting PROV-JSON and PROV-XML'

extra:
  recipe-maintainers:
    - chrisfilo
    - satra
    - trungdong
