{% set version = "1.5.3" %}

package:
  name: prov
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/prov/prov-{{ version }}.tar.gz
  sha256: a0c951107eafd508d5a26caa54863dc11fee3da86778db2a559d32450d2030a9

build:
  number: 1
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - pip
    - python
    - setuptools
    - python-dateutil >=2.2
    - networkx >=2.0
    - lxml >=3.3.5
    - six >=1.9.0
    - rdflib >=4.2.2
    - pydot >=1.2.0

  run:
    - python
    - python-dateutil >=2.2
    - networkx >=2.0
    - lxml >=3.3.5
    - six >=1.9.0
    - rdflib >=4.2.2
    - pydot>=1.2.0

test:
  # Python imports
  imports:
    - prov
    - prov.serializers
    - prov.tests

about:
  home: https://github.com/trungdong/prov
  license: MIT
  summary: 'A library for W3C Provenance Data Model supporting PROV-JSON and PROV-XML'

extra:
  recipe-maintainers:
    - chrisfilo
    - satra
    - trungdong
