{% set version = "3.2.0" %}

package:
  name: prov
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/prov/prov-{{ version }}.tar.gz
  sha256: d63bb8c037435db2e8aa4b1bda900423d69d7b82af9e3f03cd2407201f0deaae

build:
  number: 0

outputs:
  - name: prov-core
    script: build_prov_core.sh
    build:
      noarch: python
    requirements:
      host:
        - pip
        - python {{ python_min }}
        - setuptools
        - wheel
      run:
        - python >={{ python_min }}
    test:
      requires:
        - python {{ python_min }}
        - pip
      imports:
        - prov
        - prov.serializers
        - prov.model
      commands:
        - pip check
        - prov-convert --help
        - prov-compare --help
    about:
      home: https://github.com/trungdong/prov
      license: MIT
      license_file: LICENSE
      summary: A library for the W3C Provenance Data Model, supporting PROV-JSON, PROV-N and PROV-JSONLD, without the optional rdf/xml/dot/graph extras

  - name: prov
    build:
      noarch: python
    requirements:
      host:
        - python {{ python_min }}
      run:
        - python >={{ python_min }}
        - {{ pin_subpackage('prov-core', exact=True) }}
        - networkx >=2.0
        - pydot >=1.2.0
        - lxml >=3.3.5
        - rdflib >=7.0.0,<8
    test:
      requires:
        - python {{ python_min }}
        - pip
      imports:
        - prov
        - prov.serializers
        - prov.model
        - prov.dot
        - prov.graph
      commands:
        - pip check
        - prov-convert --help
        - prov-compare --help

about:
  home: https://github.com/trungdong/prov
  license: MIT
  license_file: LICENSE
  summary: A library for W3C Provenance Data Model supporting PROV-JSON, PROV-XML, PROV-JSONLD and PROV-O (RDF)

extra:
  recipe-maintainers:
    - satra
    - trungdong
