{% set version = "1.5.3" %}

package:
  name: prov
  version: {{ version }}

source:
  fn: {{ version }}.tar.gz
  url: https://github.com/trungdong/prov/archive/{{ version }}.tar.gz
  sha256: 499b46dfc96ed88dd7ca28ff0fdb89a7c9bd8e4956857efd3aa31fa97313a538

build:
  noarch: python
  number: 0
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
    - python-dateutil >=2.2
    - networkx >=2.0
    - lxml >=3.3.5
    - pydotplus >=2.0.2
    - six >=1.9.0
    - rdflib >=4.2.2

  run:
    - python
    - python-dateutil >=2.2
    - networkx >=2.0
    - lxml >=3.3.5
    - pydotplus >=2.0.2
    - six >=1.9.0
    - rdflib >=4.2.2

test:
  # Python imports
  imports:
    - prov
    - prov.serializers
    - prov.tests

about:
  home: https://github.com/trungdong/prov
  license: MIT
  summary: 'A library for W3C Provenance Data Model supporting PROV-JSON and PROV-XML'

extra:
  recipe-maintainers:
    - chrisfilo
    - satra
    - trungdong
