{% set version = "1.5.1" %}

package:
  name: prov
  version: {{ version }}

source:
  fn: prov-{{ version }}.tar.gz
  url: https://files.pythonhosted.org/packages/0a/80/bb3756a77340917a584fc0141fa70f4c51dac130724eca6033e847bdfdfa/prov-{{ version }}.tar.gz
  sha256: 7a2d72b0df43cd9c6e374d815c8ce3cd5ca371d54f98f837853ac9fcc98aee4c

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - python
    - setuptools
    - python-dateutil >=2.2
    - networkx >=1.10
    - lxml >=3.3.5
    - pydotplus >=2.0.2
    - six >=1.9.0
    - rdflib >=4.2.1

  run:
    - python
    - python-dateutil >=2.2
    - networkx >=1.10
    - lxml >=3.3.5
    - pydotplus >=2.0.2
    - six >=1.9.0
    - rdflib >=4.2.1

test:
  # Python imports
  imports:
    - prov
    - prov.serializers
    - prov.tests

about:
  home: https://github.com/trungdong/prov
  license: MIT
  summary: 'A library for W3C Provenance Data Model supporting PROV-JSON and PROV-XML'

extra:
  recipe-maintainers:
    - chrisfilo
    - satra
    - trungdong
