{% set version = "2.5.0" %}

package:
  name: prov
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/p/prov/prov-{{ version }}.tar.gz
  sha256: b0cbb56faf9305fe1ce82820294f58a19d2a45ee42afafec530f0cc5190188c4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
    - wheel

  run:
    - python >={{ python_min }}
    - python-dateutil >=2.2
    - networkx >=2.0
    - pydot >=1.2.0
    - lxml >=3.3.5
    - rdflib >=6.0.0,<8

test:
  requires:
    - python {{ python_min }}
    - pip
  imports:
    - prov
    - prov.serializers
    - prov.model
  commands:
    - pip check
    - prov-convert --help
    - prov-compare --help

about:
  home: https://github.com/trungdong/prov
  license: MIT
  license_file: LICENSE
  summary: A library for W3C Provenance Data Model supporting PROV-JSON, PROV-XML and PROV-O (RDF)

extra:
  recipe-maintainers:
    - satra
    - trungdong
