travis:
  secure:
    BINSTAR_TOKEN: QSSGrTzQjTxYeyAmrml7WOBKPkMMxVU0VgYjCr2kH68y+cnfrwtIh5EUYvM11MUWQLM99gEMcxxbGrFb5qoTJCcwHOW7xPD1N67HY+WVlvYxC/REYtxFcfu7se45XGoM0RCdwKtRTBCJWM16Ce1P1yknVWivtnivmoaea/N/IvwwGgdpN7kZUrSKniaeyOSSrOtzc/SU1lIYKHLckRUM1mhq6lig4If53HZ/rbMXm7shccvORGPDX3vCUti2pr0KCazurF3in/NlvhaDvtnL4jM4/Tenl/NgVSBTP5rzL3fwV+tSfh6GvPhxSyUXkrkUPdcCTAJFfhS53rKate0eFRNQSgCv5FUyT7ypeeRKbBfEjMimR6VETGgpm66HP8gPlQLdzmTuzu/ivrBVCTmjSmcGuAZOwLpUN5BWC6aST1ALnHd5x9jOSAaxju7kkJYV2pNQBvlyu5LNRvwKnCgNrSP/UKR2+9x+iHybcFZnI3WUOcUg3Q+B1O44Z22puRTp1n4YdWdSwt0ovjIJR9I3cuKpIe4oK1NSroTOSaJ4bCnIwDW65ORrfzD15gRUduS5na5uNMXRlmnjNoy4brlUc3SoNhLN2u3okv5kMi7W/yQ9Nm9XlRGeggjjBLj5vps8ree7Ti1dcGOTUYSKdVH1LwWguvLifYBvfM3JjyHDu8o=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
