travis:
  secure:
    BINSTAR_TOKEN: J/8yPNrHZIMBElS7SE9WiTnXP5YZgy3VwNoZiIkJqOG4RjufZAgESBHIvZWqioed2SHGwmMyTtIjmtjJL02E+N9tmWp1+cMtgArl0158nE1RKPoVS5T/hk9U+VUFFgR7hDXoovoqPko+ENuEROcVFCNkRe8EJLCpcaRXYZC57mn/NnoF294n4g3D1QsJP1O9VDK/WT/KEMWULMQ/czaKUm5483toMtTMct2Em8TYbmNQmFH0POXQU5K6ULvmzo4SxARZvmi+wdodLbEMKE4UUB/XcwuBh759Dm+alZLpu7Jkovc9Xx9D3uJjqnUuuGTrUa1RmbreC9aNU0vbgZRJw1GCBfO1RYDzy/xZF8UbJKK1N3MsW3Gu9MA1XH7Bc7d+dmH8hrb2T5RCjhy9wMIO7U1maWMULyh9bnpMuqjbGf9fd+8gmXLRp9OPBVaAhu30CMbfHa0TlSOycP92DfXjH1Jx4HJDO5d9GVhIJ0SxWZLcm+OGAFcFdsaQ/X50r1PAeuIiZBZD52FbnzVGZCMt5saCjyj4chWwDISHdO4rII3rLG9ngIE+rzXZ1tBW5WmKDzSvQ3zaL1JgVk5UlpiDBPNyk+ZAvEJYjdfN6NwZVf8i7Go2l2/i+1cLedV6W/qLX9NS5ZkWzT8v8t7SAQ8QTU4LVAFKzjegDxIig2/DTmg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
